using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CTClasses
{
    public abstract class Person
    {
        //private fields
        private string _personId;            //PK auto generated by DB, not put in by user
        private string _lastName;
        private string _firstName;
        private string _gender;
        private string _race;
        private string _dob;
        private string _ssn;
        private string _streetAddress;
        private string _apartment;
        private string _city;
        private string _state;
        private string _zip;
        private string _email;
        private string _homePhone;
        private string _mobilePhone;
        private string _workPhone;
        private string _churchConnection;
        private string _milDependent;
        private string _type;

        public Person()//no arg constructor
        { }



        //Constructor with parameters, add in int personID when DB goes live
        public Person(string personId, string lastName, string firstName, string gender, string race, string dob,
            string ssn, string streetAddress, string apartment, string city, string state,
            string zip, string email, string homePhone, string mobilePhone, string workPhone,
            string churchConnection, string milDependent, string type)

        {


             _personId = personId;// auto generated DB PK
            _lastName = lastName;
            _firstName = firstName;
            _gender = gender;
            _race = race;
            _dob = dob;
            _ssn = ssn;
            _streetAddress = streetAddress;
            _apartment = apartment;
            _city = city;
            _state = state;
            _zip = zip;
            _email = email;
            _homePhone = homePhone;
            _mobilePhone = mobilePhone;
            _workPhone = workPhone;
            _churchConnection = churchConnection;
            _milDependent = milDependent;
            _type = type;
        }
        public string personId                           //for use when DB is live
        {
            get { return _personId; }
            set { _personId = value; }
        }

        public string lastName
        {
            get { return _lastName; }
            set { _lastName = value; }
        }
        public string firstName
        {
            get { return _firstName; }
            set { _firstName = value; }
        }
        public string gender
        {
            get { return _gender; }
            set { _gender = value; }
        }
        public string race
        {
            get { return _race; }
            set { _race = value; }
        }
        public string dob
        {
            get { return _dob; }
            set { _dob = value; }
        }
        public string ssn
        {
            get { return _ssn; }
            set { _ssn = value; }
        }
        public string milDependent
        {
            get { return _milDependent; }
            set { _milDependent = value; }
        }
        public string churchConnection
        {
            get { return _churchConnection; }
            set { _churchConnection = value; }
        }
        public string streetAddress
        {
            get { return _streetAddress; }
            set { _streetAddress = value; }
        }
        public string apartment
        {
            get { return _apartment; }
            set { _apartment = value; }
        }
        public string city
        {
            get { return _city; }
            set { _city = value; }
        }
        public string state
        {
            get { return _state; }
            set { _state = value; }
        }
        public string zip
        {
            get { return _zip; }
            set { _zip = value; }
        }
        public string email
        {
            get { return _email; }
            set { _email = value; }
        }
        public string homePhone
        {
            get { return _homePhone; }
            set { _homePhone = value; }
        }
        public string mobilePhone
        {
            get { return _mobilePhone; }
            set { _mobilePhone = value; }
        }
        public string workPhone
        {
            get { return _workPhone; }
            set { _workPhone = value; }
        }

        public string type
        {
            get { return _type; }
            set { _type = value; }
        }
    }
}
