using System;

public abstract class Person
{
    //private fields
    private int _personID;//PK auto generated by DB, not put in by user
    private string _lastName;
    private string _firstName;
    private DateTime _dateOfBirth;
    private string _socialSecurityNumber;
    private string _streetAddress;
    private string _apartment;
    private string _city;
    private readonly string _state = "NC";
    private int _zip;
    private string _email;
    private string _telephone1;
    private string _telephone2;
    private string _telephone3;
    private string _demographic;
    private string _faithConnection;
    private bool _military;

    //getters and setters
    public int personID { get => _personID; }  //no setter, only a getter
    public string LastName { get => _lastName; set => _lastName = value; }
    public string FirstName { get => _firstName; set => _firstName = value; }
    public DateTime DateOfBirth { get => _dateOfBirth; set => _dateOfBirth = value; }
    public string SocialSecurityNumber { get => _socialSecurityNumber; set => _socialSecurityNumber = value; }
    public string StreetAddress { get => _streetAddress; set => _streetAddress = value; }
    public string Apartment { get => _apartment; set => _apartment = value; }
    public string City { get => _city; set => _city = value; }
    public string State { get => _state; }  //no setter
    public int Zip { get => _zip; set => _zip = value; }
    public string Email { get => _email; set => _email = value; }
    public string Telephone1 { get => _telephone1; set => _telephone1 = value; }
    public string Telephone2 { get => _telephone2; set => _telephone2 = value; }
    public string Telephone3 { get => _telephone3; set => _telephone3 = value; }
    public string Demographic { get => _demographic; set => _demographic = value; }
    public string FaithConnection { get => _faithConnection; set => _faithConnection = value; }
    public bool Military { get => _military; set => _military = value; }

    //Constructor
    public Person(string lastName, string firstName, DateTime dateOfBirth,
        string socialSecurityNumber, string streetAddress, string apartment,
        string city,
        int zip, string email, string tel1, string tel2, string tel3,
        string demographic, string faithConnection, bool military)  
	{
        personID = _personID;// auto generated DB PK
        LastName = lastName;
        FirstName = firstName;
        DateOfBirth = dateOfBirth;
        SocialSecurityNumber = socialSecurityNumber;
        StreetAddress = streetAddress;
        Apartment = apartment;
        City = city;
        _state = "NC";
        Zip = zip;
        Email= email;
        Telephone1 = tel1;
        Telephone2 = tel2;
        Telephone3 = tel3;
        Demographic = demographic;
        FaithConnection = faithConnection;
        Military = military;
	}
    
}
